# -*- coding: utf-8 -*-
"""Contents Embeddings Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4ihmI2xA9p5mc_N6ifyj27qnYCQDy2S
"""

import pandas as pd

so_df = pd.read_csv('southpark2.csv')
so_df.head()

import pickle

with open('embeddings_southpark.pkl', 'rb') as file:
  question_embeddings = pickle.load(file)

print("Shape: " + str(question_embeddings.shape))
print(question_embeddings)

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

clustering_dataset = question_embeddings

n_clusters = 2
kmeans = KMeans(
  n_clusters=n_clusters,
  random_state=0,
  n_init = 'auto').fit(clustering_dataset)

kmeans_labels = kmeans.labels_
kmeans_labels.shape

PCA_model = PCA(n_components=2)
PCA_model.fit(clustering_dataset)
new_values = PCA_model.transform(clustering_dataset)
new_values.shape

!pip install plotly

import plotly.express as px
fig = px.scatter(so_df["phrase"], x=new_values[:,0],y=new_values[:,1], color=kmeans_labels, hover_data=["phrase"])
fig.show()

so_df["category"] = kmeans_labels
so_df

from google.colab import files
so_df.to_csv('contents_clustering.csv')
#files.download('contents_clustering.csv')